[models]
default = "nrp:glm-4.7"
recent = "nrp:glm-4.7"

[models.providers.nrp]
class_path = "langchain_openai:ChatOpenAI"
models = [
    "glm-4.7",
]
api_key_env = "ZAI_API_KEY"
base_url = "https://api.z.ai/api/coding/paas/v4"

[models.providers.nrp.params]
temperature = 0
